### ISSUE TITLE
[+orion] Bug 'marvel hangman'

### ISSUE THREAD

**Issue by orion-botx** [sugaroidbot/sugaroid#109]
The following answer was a given by sugaroid, and is considered as a bug. Please 
	manually review this issue, and close it if it looks unnecessary.

	user: marvel hangman 
    sugaroid: An unhandled exception occurred: Traceback (most recent call last):
  File "telegram_bot.py", line 162, in on_message
    response = str(sg.parse(msg))
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/sugaroid.py", line 254, in parse
    response = self.neuron.parse(args)
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/brain/brain.py", line 76, in parse
    response = self.gen_best_match(preprocessed)
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/brain/brain.py", line 101, in gen_best_match
    return self.bot.get_response(parsed)
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/core/bot.py", line 361, in get_response
    response = self.generate_response(
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/core/bot.py", line 148, in generate_response
    output = adapter.process(
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/brain/hangman/__init__.py", line 214, in process
    self.chatbot.globals["hangman"]["class"] = Hangman(
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/brain/hangman/__init__.py", line 103, in __init__
    self.word = random_response(get_hangman_words("marvel", chatbot.session))
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/brain/hangman/constants.py", line 14, in get_hangman_words
    data = collector.get_dataset(f"hangman/{category}").splitlines()
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/datasets/collector.py", line 70, in get_dataset
    raise RuntimeError(f"{r.status_code}, {r.reason}: {txt_api_endpoint}")
RuntimeError: 404, Not Found: https://raw.githubusercontent.com/sugaroidbot/datasets/main/datasets/hangman/marvel.txt

**Comment by srevinsaju** [comment]
Fixed in https://github.com/sugaroidbot/datasets/commit/9da7b50dc7a1f42cf0464d700bf0e4f99dc033f3
