### ISSUE TITLE
[+orion] Bug ''''

### ISSUE THREAD

**Issue by orion-botx** [sugaroidbot/sugaroid#112]
The following answer was a given by sugaroid, and is considered as a bug. Please 
	manually review this issue, and close it if it looks unnecessary.

	user: '' 
    sugaroid: An unhandled exception occurred: Traceback (most recent call last):
  File "telegram_bot.py", line 162, in on_message
    response = str(sg.parse(msg))
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/sugaroid.py", line 255, in parse
    response = self.neuron.parse(args)
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/brain/brain.py", line 76, in parse
    response = self.gen_best_match(preprocessed)
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/brain/brain.py", line 101, in gen_best_match
    return self.bot.get_response(parsed)
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/core/bot.py", line 361, in get_response
    response = self.generate_response(
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/core/bot.py", line 146, in generate_response
    if adapter.can_process(input_statement):
  File "/app/.heroku/python/lib/python3.8/site-packages/sugaroid/brain/have.py", line 20, in can_process
    return statement.words[0] == "have" and not statement.words[-1].endswith("?")
IndexError: list index out of range

**Comment by srevinsaju** [comment]
Fixed on master
